services:
  - type: web
    name: samachar-news
    runtime: python
    repo: https://github.com/OK45batwal/samachar-news
    branch: main
    buildCommand: pip install -r requirements.txt
    plan: free
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips '*'
    envVars:
      - key: SUPERTOKENS_CONNECTION_URI
        value: https://try.supertokens.com
      - key: SAMACHAR_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: samachar-news
          envVarKey: RENDER_EXTERNAL_URL
      - key: PROMETHEUS_ENABLED
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: samachar-news-db
          property: connectionString

databases:
  - name: samachar-news-db
    plan: free
    ipAllowList: []
