"""add ingestion_runs table

Revision ID: 6cc476418190
Revises: ae77d660d204
Create Date: 2026-06-30 21:34:30.169703

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cc476418190'
down_revision: Union[str, Sequence[str], None] = 'ae77d660d204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_feeds', sa.Integer(), nullable=True),
    sa.Column('feeds_succeeded', sa.Integer(), nullable=True),
    sa.Column('feeds_failed', sa.Integer(), nullable=True),
    sa.Column('articles_added', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
